CC := gcc
Filename := client.c 
Finish := client

SERV_PORT 		:= "6666"   		#端口号
SERV_IP_ADDR 	:= "192.168.0.3"    #IP


all:
	$(CC) $(Filename) -o $(Finish)


clean:
	-rm $(Finish)

#run:
#	./$(Finish) 	#$(SERV_IP_ADDR) $(SERV_PORT)


